### ISSUE TITLE
install project on amazon ec2 CH dev

### ISSUE THREAD

**Issue by pprolancer** [Heteroskedastic/chills-pos#9]

**Comment by pprolancer** [comment]
@vincentdavis 
This project installed on ec2 Heteroskedastic-Dev:
just I need you to update DNS record of store.cinnamonhills.org to this ec2 machine ip.
Heteroskedastic-Dev ec2 ip is: 35.164.55.7

**Comment by vincentdavis** [comment]
done.
@pprolancer please update the spreadsheet
https://docs.google.com/spreadsheets/d/1_fYdTYnnKy6OK1MlzAvXUPm11XSEoBKWoJJXy6oGfAw/edit#gid=0
